package org.aggelos.baztag.api.xml;

public enum ApiAnswers {

	ABUSESENDING,
	NOGOODTOKENORSERIAL,
	MESSAGENOTSENT,
	NABCASTNOTSENT,
	NABCASTSENT,
	MESSAGESENT,
	TTSSENT,
	TTSNOTSENT,
	CHORSENT,
	CHORNOTSENT,
	EARPOSITIONSENT,
	EARPOSITIONNOTSENT,
	WEBRADIOSENT,
	WEBRADIONOTSENT,
	NOCORRECTPARAMETERS,
	NOTV2RABBIT,
	COMMANDSENT,
	POSITIONEAR
	;
	
	
}
